/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#393842",
        "background": "#13131b",
        "secondary": "#ffb95f",
        "primary": "#46f1c5",
        "on-background": "#e4e1ed",
        "surface-container-highest": "#34343d",
        "outline-variant": "#3b4a44",
        "on-surface-variant": "#bacac2",
        "on-surface": "#e4e1ed",
        "on-secondary-fixed-variant": "#653e00",
        "on-error": "#690005",
        "surface-container": "#1f1f28",
        "primary-fixed": "#55fcd0",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#28dfb5",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-container": "#9b0015",
        "tertiary-fixed": "#ffdad7",
        "surface-container-lowest": "#0d0d16",
        "error-container": "#93000a",
        "inverse-surface": "#e4e1ed",
        "tertiary-container": "#ffa39c",
        "tertiary-fixed-dim": "#ffb3ad",
        "surface-container-high": "#292932",
        "on-secondary-fixed": "#2a1700",
        "on-tertiary": "#68000a",
        "surface-tint": "#28dfb5",
        "secondary-fixed-dim": "#ffb95f",
        "surface-dim": "#13131b",
        "surface-variant": "#34343d",
        "on-error-container": "#ffdad6",
        "primary-container": "#00d4aa",
        "on-tertiary-fixed-variant": "#930013",
        "inverse-primary": "#006b55",
        "on-primary": "#00382b",
        "tertiary": "#ffcbc6",
        "on-primary-fixed": "#002118",
        "inverse-on-surface": "#302f39",
        "surface": "#13131b",
        "secondary-container": "#ee9800",
        "on-primary-fixed-variant": "#00513f",
        "surface-container-low": "#1b1b23",
        "on-secondary-container": "#5b3800",
        "on-primary-container": "#005643",
        "on-secondary": "#472a00",
        "secondary-fixed": "#ffddb8",
        "outline": "#85948d"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
